---
#Distro agnostic tasks go here
- name: Change hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Disallow SSH password connections
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config

- name: Restart SSH service
  systemd:
    name: sshd
    state: restarted

- name: Install Netdata
  raw: "bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait"

- name: Include distro specific tasks
  include: "{{ ansible_os_family|lower }}.yml"