---
#Distro agnostic tasks go here
- name: Change hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Disallow SSH password connections
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin without-password'

- name: Restart SSH service
  systemd:
    name: sshd
    state: restarted

- name: Install Netdata
  raw: "bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait"

- name: Include distro specific tasks
  include: "{{ ansible_os_family|lower }}.yml"