---
#Distro agnostic tasks go here
- name: Disallow SSH password connections
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin without-password'

- name: Restart SSH service
  systemd:
    name: sshd
    state: restarted

- name: Minimum swapiness
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^vm.swappiness"
    line: "vm.swappiness = 10"
  register: swapiness

- name: Commit swapiness changes
  command: "sysctl vm.swappiness=10"
  when: swapiness.changed

- name: Download Netdata installation script
  get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: /tmp/netdata-install.sh
    mode: 0744

- name: Run Netdata installation script
  shell: /tmp/netdata-install.sh --dont-wait
  args:
    creates: /etc/netdata/netdata.conf

- name: Install aptitude
  apt:
    name: aptitude
    state: latest

- name: Update APT
  apt:
    name: "*"
    state: latest

- name: Install base packages
  apt:
    name: "{{ base_packages }}"
    state: latest
  vars:
    base_packages:
      - htop
      - screen
      - vim
      - git
      - curl
      - unzip
      - nfs-common
      - nmap
      - net-tools
      - tree
      - zsh

#- name: Include docker installation tasks
#  include_tasks: docker-install.yml

- name: Include unattended-upgrades tasks
  include_tasks: unattended-upgrades.yml