---
- name: Ensure zsh is installed
  apt:
    name: zsh
    state: latest

- name: Run oh-my-zsh installation script
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "/home/{{ ansible_user }}/.oh-my-zsh/"

- name: Change prompt color
  lineinfile:
    path: "/home/{{ ansible_user }}/.oh-my-zsh/themes/robbyrussell.zsh-theme"
    regexp: '^PROMPT'
    line: "PROMPT='%{$fg_bold[black]%}%M ${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'"