---
- name: YUM update
  yum:
    name: "*"
    state: latest
  become: true

- name: Install epel-release
  yum:
    name: epel-release
    state: latest
  become: true

- name: Install packages
  yum:
    name: "{{ common_packages + redhat_packages}}"
    state: latest
  become: true

- name: Include yum-cron tasks
  include_tasks: yum-cron.yml

