---
- name: Install tilix
  apt:
    name: tilix
    state: latest

- name: Add tilix conditional to .bashrc
  blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    block: |
      if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
      fi
    marker: ""

- name: Add tilix conditional to .zshrc
  blockinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    block: |
      if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
      fi
    marker: ""

- name: Create tilix symbolic link
  file:
    src: /etc/profile.d/vte-2.91.sh
    dest: /etc/profile.d/vte.sh
    state: link